# Centralized configuration for api-gateway in the 'local' environment
# Defines all service routes for running locally, connecting to other services via localhost.

spring:
  cloud:
    gateway:
      # Defines the routing rules for incoming requests to downstream services.
      routes:
        - id: notification-service
          uri: lb://notification-service # The 'lb://' prefix enables client-side load balancing with Eureka.
          predicates:
            - Path=/sendEmail/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: load-product
          uri: lb://load-product
          predicates:
            - Path=/productFile/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

eureka:
  # Configures how this service interacts with the Eureka discovery server.
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Use localhost for local development and debugging.
    enabled: true
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost
    # Explicitly set the instance-id to override the default hostname resolution.
    # This prevents Spring Cloud from picking up 'host.docker.internal' from the environment if docker desktop is running
    # and ensures it registers with 'localhost' as you intend.
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    metadata-map:
      # These tags tell Prometheus to scrape this service.
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/actuator/prometheus'


management:
  # Configures actuator endpoints for monitoring and management.
  endpoints:
    web:
      exposure:
        # Securely expose only necessary endpoints. 'gateway' is useful for API Gateways.
        include: "health,info,prometheus,gateway"
  endpoint:
    # Disables the remote shutdown endpoint, which is a critical security measure.
    shutdown:
      enabled: false
  metrics:
    # Adds the application name as a default tag to all metrics for better filtering.
    tags:
      application: ${spring.application.name}