# Centralized configuration for user-service in the 'dev' environment
# Configures the service for development with an H2 database and RabbitMQ.

spring:
  # Configures the connection to the development database.
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  # Configures JPA and Hibernate for development.
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Automatically creates/updates the database schema on startup.
    show-sql: true
  # Enables the H2 database web console for debugging.
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true # Allows access to the console from other machines.
  # Configures Spring Cloud Stream for message-driven communication.
  cloud:
    stream:
      # Binds an output channel to a specific RabbitMQ destination.
      bindings:
        send-communication-out-0:
          destination: send-communication
          group: ${spring.application.name}
  # Configures the connection to the RabbitMQ message broker.
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

eureka:
  # Configures how this service interacts with the Eureka discovery server.
  instance:
    # This is crucial for Prometheus to get the container's internal IP inside Docker
    prefer-ip-address: true
    metadata-map:
      # These tags tell Prometheus to scrape this service.
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/actuator/prometheus'
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    enabled: true
    fetchRegistry: true
    registerWithEureka: true

management:
  # Configures actuator endpoints for monitoring and management.
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    # Disables the remote shutdown endpoint, which is a critical security measure.
    shutdown:
      enabled: false
  metrics:
    # Adds the application name as a default tag to all metrics for better filtering.
    tags:
      application: ${spring.application.name}